name: frontend_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  sqflite: ^2.3.3
  path: ^1.9.0
  connectivity_plus: ^6.0.3
  shared_preferences: ^2.3.2
  csv: ^5.1.1
  path_provider: ^2.1.1
  share_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
